//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfWriterService.Consumer.PdfServiceV2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="PdfWriterService.V2", ConfigurationName="PdfServiceV2.PdfWriterServiceV2")]
    public interface PdfWriterServiceV2 {
        
        // CODEGEN: Generating message contract since the wrapper namespace (PdfWriterService.V1) of message HelloWorldRequest does not match the default value (PdfWriterService.V2)
        [System.ServiceModel.OperationContractAttribute(Action="PdfWriterService.V1/PdfWriterServiceV1/HelloWorld", ReplyAction="PdfWriterService.V1/PdfWriterServiceV1/HelloWorldResponse")]
        PdfWriterService.Consumer.PdfServiceV2.HelloWorldResponse HelloWorld(PdfWriterService.Consumer.PdfServiceV2.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PdfWriterService.V2/PdfWriterServiceV2/HelloWorld2", ReplyAction="PdfWriterService.V2/PdfWriterServiceV2/HelloWorld2Response")]
        string HelloWorld2(string name);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorld", WrapperNamespace="PdfWriterService.V1", IsWrapped=true)]
    public partial class HelloWorldRequest {
        
        public HelloWorldRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorldResponse", WrapperNamespace="PdfWriterService.V1", IsWrapped=true)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="PdfWriterService.V1", Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PdfWriterServiceV2Channel : PdfWriterService.Consumer.PdfServiceV2.PdfWriterServiceV2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PdfWriterServiceV2Client : System.ServiceModel.ClientBase<PdfWriterService.Consumer.PdfServiceV2.PdfWriterServiceV2>, PdfWriterService.Consumer.PdfServiceV2.PdfWriterServiceV2 {
        
        public PdfWriterServiceV2Client() {
        }
        
        public PdfWriterServiceV2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PdfWriterServiceV2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PdfWriterServiceV2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PdfWriterServiceV2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PdfWriterService.Consumer.PdfServiceV2.HelloWorldResponse PdfWriterService.Consumer.PdfServiceV2.PdfWriterServiceV2.HelloWorld(PdfWriterService.Consumer.PdfServiceV2.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            PdfWriterService.Consumer.PdfServiceV2.HelloWorldRequest inValue = new PdfWriterService.Consumer.PdfServiceV2.HelloWorldRequest();
            PdfWriterService.Consumer.PdfServiceV2.HelloWorldResponse retVal = ((PdfWriterService.Consumer.PdfServiceV2.PdfWriterServiceV2)(this)).HelloWorld(inValue);
            return retVal.HelloWorldResult;
        }
        
        public string HelloWorld2(string name) {
            return base.Channel.HelloWorld2(name);
        }
    }
}
