//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfWriterService.Consumer.PdfSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReburnDTO", Namespace="PdfWriterService.Models")]
    [System.SerializableAttribute()]
    public partial class ReburnDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        private string CustomrNameField;
        
        private string EmployeeResponsibleIDField;
        
        private string IssueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomrName {
            get {
                return this.CustomrNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomrNameField, value) != true)) {
                    this.CustomrNameField = value;
                    this.RaisePropertyChanged("CustomrName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EmployeeResponsibleID {
            get {
                return this.EmployeeResponsibleIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeResponsibleIDField, value) != true)) {
                    this.EmployeeResponsibleIDField = value;
                    this.RaisePropertyChanged("EmployeeResponsibleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Issue {
            get {
                return this.IssueField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueField, value) != true)) {
                    this.IssueField = value;
                    this.RaisePropertyChanged("Issue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="PdfWriterService.V3", ConfigurationName="PdfSvc.PdfWriterServiceV3")]
    public interface PdfWriterServiceV3 {
        
        // CODEGEN: Generating message contract since the wrapper namespace (PdfWriterService.V1) of message HelloWorldRequest does not match the default value (PdfWriterService.V3)
        [System.ServiceModel.OperationContractAttribute(Action="PdfWriterService.V1/PdfWriterServiceV1/HelloWorld", ReplyAction="PdfWriterService.V1/PdfWriterServiceV1/HelloWorldResponse")]
        PdfWriterService.Consumer.PdfSvc.HelloWorldResponse HelloWorld(PdfWriterService.Consumer.PdfSvc.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (PdfWriterService.V2) of message HelloWorld2Request does not match the default value (PdfWriterService.V3)
        [System.ServiceModel.OperationContractAttribute(Action="PdfWriterService.V2/PdfWriterServiceV2/HelloWorld2", ReplyAction="PdfWriterService.V2/PdfWriterServiceV2/HelloWorld2Response")]
        PdfWriterService.Consumer.PdfSvc.HelloWorld2Response HelloWorld2(PdfWriterService.Consumer.PdfSvc.HelloWorld2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PdfWriterService.V3/PdfWriterServiceV3/GenerateReburnPDF", ReplyAction="PdfWriterService.V3/PdfWriterServiceV3/GenerateReburnPDFResponse")]
        byte[] GenerateReburnPDF(PdfWriterService.Consumer.PdfSvc.ReburnDTO reburnDto);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorld", WrapperNamespace="PdfWriterService.V1", IsWrapped=true)]
    public partial class HelloWorldRequest {
        
        public HelloWorldRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorldResponse", WrapperNamespace="PdfWriterService.V1", IsWrapped=true)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="PdfWriterService.V1", Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorld2", WrapperNamespace="PdfWriterService.V2", IsWrapped=true)]
    public partial class HelloWorld2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="PdfWriterService.V2", Order=0)]
        public string name;
        
        public HelloWorld2Request() {
        }
        
        public HelloWorld2Request(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorld2Response", WrapperNamespace="PdfWriterService.V2", IsWrapped=true)]
    public partial class HelloWorld2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="PdfWriterService.V2", Order=0)]
        public string HelloWorld2Result;
        
        public HelloWorld2Response() {
        }
        
        public HelloWorld2Response(string HelloWorld2Result) {
            this.HelloWorld2Result = HelloWorld2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PdfWriterServiceV3Channel : PdfWriterService.Consumer.PdfSvc.PdfWriterServiceV3, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PdfWriterServiceV3Client : System.ServiceModel.ClientBase<PdfWriterService.Consumer.PdfSvc.PdfWriterServiceV3>, PdfWriterService.Consumer.PdfSvc.PdfWriterServiceV3 {
        
        public PdfWriterServiceV3Client() {
        }
        
        public PdfWriterServiceV3Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PdfWriterServiceV3Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PdfWriterServiceV3Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PdfWriterServiceV3Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PdfWriterService.Consumer.PdfSvc.HelloWorldResponse PdfWriterService.Consumer.PdfSvc.PdfWriterServiceV3.HelloWorld(PdfWriterService.Consumer.PdfSvc.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            PdfWriterService.Consumer.PdfSvc.HelloWorldRequest inValue = new PdfWriterService.Consumer.PdfSvc.HelloWorldRequest();
            PdfWriterService.Consumer.PdfSvc.HelloWorldResponse retVal = ((PdfWriterService.Consumer.PdfSvc.PdfWriterServiceV3)(this)).HelloWorld(inValue);
            return retVal.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PdfWriterService.Consumer.PdfSvc.HelloWorld2Response PdfWriterService.Consumer.PdfSvc.PdfWriterServiceV3.HelloWorld2(PdfWriterService.Consumer.PdfSvc.HelloWorld2Request request) {
            return base.Channel.HelloWorld2(request);
        }
        
        public string HelloWorld2(string name) {
            PdfWriterService.Consumer.PdfSvc.HelloWorld2Request inValue = new PdfWriterService.Consumer.PdfSvc.HelloWorld2Request();
            inValue.name = name;
            PdfWriterService.Consumer.PdfSvc.HelloWorld2Response retVal = ((PdfWriterService.Consumer.PdfSvc.PdfWriterServiceV3)(this)).HelloWorld2(inValue);
            return retVal.HelloWorld2Result;
        }
        
        public byte[] GenerateReburnPDF(PdfWriterService.Consumer.PdfSvc.ReburnDTO reburnDto) {
            return base.Channel.GenerateReburnPDF(reburnDto);
        }
    }
}
